### ISSUE TITLE
flutter_contacts/SwiftFlutterContactsPlugin.swift:435: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by yanashenyang** [QuisApp/flutter_contacts#209]
flutter --version
Flutter 3.38.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b45fa18946 (12 days ago) • 2025-11-12 22:09:06 -0600
Engine • hash 78c3c9557e50ee7c676fa37562558c59efd8406a (revision b5990e5ccc) (12 days ago) • 2025-11-12 21:08:24.000Z
Tools • Dart 3.10.0 • DevTools 2.51.1

ios 13.0

build error
flutter_contacts/SwiftFlutterContactsPlugin.swift:435: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by fefsouza10** [comment]
Facing the same error, on Flutter 3.38.3 after migrating to use the new UISceneDelegate

**Comment by hieutv-dng** [comment]
Facing the same error when upgrade Flutter 3.38.3

**Comment by joachim-quis** [comment]
Hi! I just released [v2.0.0-beta.1](https://pub.dev/packages/flutter_contacts/versions/2.0.0-beta.1), a complete rewrite of this plugin with upgraded dependencies 🎉

Please let me know if you still encounter errors after migrating to v2.
